name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build - PHP ${{ matrix.php }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Setup Composer Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer Dependencies
        uses: php-actions/composer@v6
        with:
          args: --prefer-dist --ignore-platform-reqs
          php_version: ${{ matrix.php }}

      - name: Run tests
        run: composer test

#    - name: Run tests
#      uses: php-actions/phpunit@v2
#      with:
#        php_version: ${{ matrix.php }}
